blueprint:
  name: Sensor Light
  description: 'A simple yet fully customizable blueprint for smart lights based on motion and other sensors.'
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time after no motion (seconds)
      default: 120
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: seconds
    illuminance_sensor:
      name: (Optional) Illuminance Sensor
      default: []
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    illuminance_threshold:
      name: Illuminance Threshold
      default: 20
      selector:
        number:
          min: 0
          max: 1000
    sun_elevation:
      name: (Optional) Sun Elevation Max
      description: Only turn lights on if sun is below this elevation
      default: 5
      selector:
        number:
          min: -10
          max: 90

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: 'on'
  - platform: state
    entity_id: !input motion_sensor
    from: 'on'
    to: 'off'
    for:
      seconds: !input no_motion_wait

condition: []

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input motion_sensor
            state: 'on'
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id: !input illuminance_sensor
                below: !input illuminance_threshold
              - condition: numeric_state
                entity_id: sun.sun
                attribute: elevation
                below: !input sun_elevation
        sequence:
          - service: light.turn_on
            target: !input light_target
    default:
      - service: light.turn_off
        target: !input light_target

mode: restart