blueprint:
  name: TuYa Smart Knob (TS004F_von_TZ3000_gwkzibhs)
  description: Automation blueprint for TuYa Smart Knob using ZHA.
  domain: automation
  input:
    remote:
      name: TuYa Knob Remote
      description: Select the remote control you want to use.
      selector:
        device:
          integration: zha

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - choose:
      # Press
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'press_type' and trigger.event.data.args[0] == 0 }}"
        sequence: []

      # Double Press
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'press_type' and trigger.event.data.args[0] == 1 }}"
        sequence: []
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_double_press' }}"
        sequence: []

      # Long Press
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'press_type' and trigger.event.data.args[0] == 2 }}"
        sequence: []
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'remote_button_long_press' }}"
        sequence: []

      # Rotate Left
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'left' }}"
        sequence: []

      # Rotate Right
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'right' }}"
        sequence: []
