blueprint:
  name: S24 Ultra — Wireless Charging Fade & Off
  description: s24wirless charger
    
  domain: automation
  input:
    battery_state:
      name: Battery state sensor
      description: Select your S24 Ultra battery state entity (should show "charging")
      selector:
        entity:
          domain: sensor

    charger_type:
      name: Charger type sensor
      description: Select your S24 Ultra charger type entity (must show "wireless")
      selector:
        entity:
          domain: sensor

    lights:
      name: Lights to control
      description: Lights that will fade and turn off
      selector:
        target:
          entity:
            domain: light

trigger:
  - platform: state
    entity_id: !input battery_state
    to: "charging"

condition:
  - condition: state
    entity_id: !input charger_type
    state: "wireless"

action:
  - service: light.turn_on
    target: !input lights
    data:
      brightness_pct: 100
      transition: 1

  - service: light.turn_on
    target: !input lights
    data:
      brightness_pct: 3
      transition: 3

  - delay: "00:20:00"
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: sensor.s24ultra_battery_state
                    state: "charging"
              - condition: not
                conditions:
                  - condition: state
                    entity_id: sensor.s24ultra_charger_type
                    state: "wireless"
                    
  sequence:
          - stop: "Charging stopped early → automation canceled."
 
  - service: light.turn_off
    target: !input lights

mode: restart
